class LoremIpsum {
  static const loremIpsum =
      """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut ornare lectus sit amet est placerat in egestas. Quam vulputate dignissim suspendisse in. Non sodales neque sodales ut etiam sit amet nisl. Purus gravida quis blandit turpis cursus in hac. Mattis vulputate enim nulla aliquet porttitor lacus. Tempus quam pellentesque nec nam. A scelerisque purus semper eget duis at tellus at urna. Ipsum faucibus vitae aliquet nec. Aliquam vestibulum morbi blandit cursus. Fermentum et sollicitudin ac orci phasellus egestas tellus. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Ornare quam viverra orci sagittis eu volutpat odio facilisis mauris. Nibh nisl condimentum id venenatis a condimentum vitae sapien.

Viverra nibh cras pulvinar mattis nunc sed blandit libero. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Id semper risus in hendrerit gravida rutrum quisque non. Sed viverra ipsum nunc aliquet bibendum. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Aliquam ut porttitor leo a diam sollicitudin tempor id. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Consequat nisl vel pretium lectus quam id leo in vitae. Vitae elementum curabitur vitae nunc sed velit. Varius duis at consectetur lorem. Augue lacus viverra vitae congue eu consequat ac felis. Tincidunt arcu non sodales neque sodales. Sed risus pretium quam vulputate dignissim suspendisse. Ornare arcu dui vivamus arcu. Sed felis eget velit aliquet sagittis id consectetur purus. Eget sit amet tellus cras adipiscing enim eu turpis egestas.

Nibh praesent tristique magna sit. In mollis nunc sed id. Neque sodales ut etiam sit amet nisl purus in. Enim praesent elementum facilisis leo vel fringilla est. At quis risus sed vulputate odio ut. Non arcu risus quis varius. Mi sit amet mauris commodo quis. Egestas tellus rutrum tellus pellentesque eu. Ut placerat orci nulla pellentesque dignissim. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Fames ac turpis egestas maecenas pharetra convallis posuere. Ullamcorper eget nulla facilisi etiam dignissim diam. Condimentum mattis pellentesque id nibh tortor id aliquet. In nulla posuere sollicitudin aliquam. Gravida cum sociis natoque penatibus et magnis dis parturient montes. Lacinia at quis risus sed vulputate odio ut enim blandit.

Congue nisi vitae suscipit tellus mauris. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Et molestie ac feugiat sed lectus vestibulum. Urna molestie at elementum eu facilisis sed odio. Leo in vitae turpis massa sed elementum tempus egestas. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Integer vitae justo eget magna fermentum iaculis eu non diam. Urna neque viverra justo nec ultrices dui sapien eget. Tincidunt id aliquet risus feugiat in ante metus dictum at. Risus nec feugiat in fermentum posuere urna nec. Pellentesque id nibh tortor id aliquet lectus proin nibh. Mattis enim ut tellus elementum sagittis vitae. Neque gravida in fermentum et sollicitudin ac orci phasellus. Tellus in hac habitasse platea dictumst vestibulum rhoncus. Id venenatis a condimentum vitae sapien pellentesque habitant morbi. Massa vitae tortor condimentum lacinia quis vel eros donec. Nulla porttitor massa id neque.

Eu facilisis sed odio morbi quis commodo odio aenean. Morbi tincidunt ornare massa eget egestas purus viverra accumsan in. Eget magna fermentum iaculis eu non diam phasellus. Mauris a diam maecenas sed enim. Massa eget egestas purus viverra accumsan in nisl nisi. Condimentum vitae sapien pellentesque habitant morbi tristique. Quis commodo odio aenean sed adipiscing. Pharetra et ultrices neque ornare aenean. Neque aliquam vestibulum morbi blandit cursus. Tortor at auctor urna nunc id. Posuere urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Dis parturient montes nascetur ridiculus mus mauris. Malesuada fames ac turpis egestas sed tempus urna. Gravida cum sociis natoque penatibus et. Sagittis vitae et leo duis.

Mattis enim ut tellus elementum sagittis vitae et leo duis. Molestie a iaculis at erat pellentesque. Id porta nibh venenatis cras sed felis. Ac tortor dignissim convallis aenean et tortor at risus viverra. Aliquet lectus proin nibh nisl condimentum id venenatis. Orci dapibus ultrices in iaculis nunc sed. Et egestas quis ipsum suspendisse ultrices gravida. Magna fermentum iaculis eu non. Diam maecenas sed enim ut sem viverra aliquet. Elementum tempus egestas sed sed risus. Neque convallis a cras semper auctor neque vitae tempus. Id faucibus nisl tincidunt eget nullam non. Porta non pulvinar neque laoreet.

Gravida rutrum quisque non tellus orci ac auctor. Pulvinar etiam non quam lacus. Feugiat sed lectus vestibulum mattis ullamcorper velit. Elementum tempus egestas sed sed risus. Pellentesque habitant morbi tristique senectus et netus et. Convallis posuere morbi leo urna molestie. Bibendum neque egestas congue quisque egestas diam in. Maecenas pharetra convallis posuere morbi leo. Ut placerat orci nulla pellentesque dignissim enim. Semper viverra nam libero justo laoreet sit amet cursus. Eget arcu dictum varius duis at consectetur lorem donec. Odio euismod lacinia at quis risus sed vulputate odio. Dui faucibus in ornare quam viverra orci.

Diam quis enim lobortis scelerisque fermentum dui faucibus. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. Convallis aenean et tortor at. Gravida in fermentum et sollicitudin ac orci phasellus egestas tellus. Bibendum ut tristique et egestas. Dignissim cras tincidunt lobortis feugiat vivamus at. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Sed viverra ipsum nunc aliquet bibendum. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra.

Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Quis enim lobortis scelerisque fermentum dui faucibus in. Turpis massa tincidunt dui ut ornare lectus sit amet est. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum. Pharetra et ultrices neque ornare. Congue quisque egestas diam in. Eget aliquet nibh praesent tristique. Odio euismod lacinia at quis risus sed vulputate odio. Gravida in fermentum et sollicitudin ac orci. Cursus vitae congue mauris rhoncus aenean vel elit. Urna nunc id cursus metus aliquam eleifend mi. Dui id ornare arcu odio ut. Faucibus et molestie ac feugiat. Egestas sed tempus urna et. Sagittis orci a scelerisque purus semper eget duis.

Venenatis a condimentum vitae sapien pellentesque habitant. Id cursus metus aliquam eleifend mi. Felis donec et odio pellentesque diam volutpat. Eget gravida cum sociis natoque penatibus et magnis dis. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Nunc sed blandit libero volutpat sed cras ornare arcu dui. Scelerisque purus semper eget duis. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Mauris ultrices eros in cursus turpis massa tincidunt. Ac feugiat sed lectus vestibulum mattis. Non odio euismod lacinia at. Elementum tempus egestas sed sed. Vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Facilisis magna etiam tempor orci. Quam lacus suspendisse faucibus interdum. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Cras fermentum odio eu feugiat pretium.
""";
}
